Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  #approot: "http://localhost:3000"
  copyright: © 2014 NICTA
  #analytics: UA-YOURCODE
  nerWebServiceUrl: http://localhost:8080/nicta-ner-web/rest/v1.0/ner

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  nerWebServiceUrl: http://ner.t3as.org/nicta-ner-web/rest/v1.0/ner
  <<: *defaults
